### ISSUE TITLE
Order progress incomplete

### ISSUE THREAD

**Issue by friedger** [hirosystems/btc-us-website#4]
I have preordered a name and then registered the name.
https://explorer.stacks.co/txid/35c50fc2d58d3105009a7d5a5541fea53bd1350f97d020de86eeb67eebbe8437?chain=mainnet
https://explorer.stacks.co/txid/878820243008a532f47b5a9d519b6982a793c4702ebe3f307533ed2b1dad718c?chain=mainnet

While the preorder was confirmed, the registration didn't because the extension used the wrong nonce.

Now, the site is in a state where I can't do anything with my account.

I tried to register the name via command line but tthe claimability period expired.
https://explorer.stacks.co/txid/0x8e91f37209a014ed29b68de629ae0e9766740ee9a0d7b073bf9918ac7ba59aca

**Comment by MarvinJanssen** [comment]
I've seen this a few times. I even managed to RBF my own transaction. See https://github.com/blockstack/stacks-wallet-web/issues/1270.

Does it show the registration as pending due to it being stuck in the mempool? (How is it even possible the second one is in the mempool at all, should've ran into a BadNonce / ConflictingNonceInMempool / RBF.)

Maybe we want the restart button to show after a period of time.

**Comment by friedger** [comment]
@MarvinJanssen The nonce was from a different account and way ahead.

Yes, a reset button would be good to show after the claim period expired.

**Comment by friedger** [comment]
@MarvinJanssen Furthermore, the status is successful even though the second tx failed.
![Screenshot from 2021-06-16 09-23-43](https://user-images.githubusercontent.com/1449049/122214451-65a4e680-ceaa-11eb-9322-282689d6a4dd.png)
